version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: directus
      POSTGRES_DB: directus
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"